### ISSUE TITLE
A question on the communication between LizGoban and engines

### ISSUE THREAD

**Issue by isty2e** [kaorahi/lizgoban#45]
I'm currently using LizGoban with KataGo, both locally and via SSH. When using the locally installed version of KataGo, though it lags a bit at high visit counts (>100k), it remains quite responsive all the time, as expected. However, when the KataGo on the GCP is attached through SSH, it lags for several seconds, or even worse, tens of seconds. This rarely happens for less visit counts (~50k), but it becomes nearly irresponsive for high number of visits (300k-2M). 

I suppose kata-analyze output is bottlenecked by the network bandwidth and probably this should be dealt with the KataGo side, but is there anything can be done from the GUI side?

**Comment by kaorahi** [comment]
I would like to confirm the situation first (though I have no clear answer anyway).

(1) What do you mean by the word "lags"? Does LizGoban react slowly for your keyboard/mouse operations? Or, are the displayed suggestions updated slowly when you leave LizGoban running without operations?

(2) Does it also happen...
* [A] with Leela Zero?
* [B] with Lizzie?
* [C] without GUI? (= if you use KataGo directly by typing GTP commands on your SSH console?)

I remember an unsolved issue on delay over SSH with both LZ and KataGo. But I'm not sure whether this is related to your problem.
https://github.com/leela-zero/leela-zero/issues/2523

**Comment by isty2e** [comment]
1) LizGoban itself normally reacts to keyboard/mouse controls. Only information (playouts, winrates, scoreleads, PVs, etc.) is displayed in a delayed manner.

2) Yes/Yes/No.

So yeah, this is not necessarily a bug or something, but just an inconvenience. I suppose it is just necessary information information (probably lz-analyze or kata-analyze) being bottlenecked by network bandwidth. `ssh -C` and reducing update frequency helps a bit, but not quite a lot.

**Comment by kaorahi** [comment]
Hmm...

If long outputs are harmful, how about writing a filter that limits the number of suggested moves?

~~~
./katago gtp -model XXX.bin.gz -config XXX.cfg | ruby -pe 'limit = 5; $stdout.sync = $stderr.sync = true; $_ =~ /^(info.*?)(( ownership.*)?)$/ and (i,o=[$1,$2]) and $_ = i.split(/(?= info)/)[0...limit].join + o + %|\n|'
~~~

(Strictly speaking, this code is incomplete because it relies on the order of "info ...".)

**Comment by isty2e** [comment]
Hm, that might help... But I wonder why it lags for higher visit counts? Maybe more candidate moves? Also I am curious if there is any possibility that the bottleneck is not the network, but parsing and post-processing. A single kata-analyze on an empty board was about 13 kB, so even with interval=20, it is 65 kB/sec, and even if there are more candidate move and longer PV's, it should not exceed 1 MB/sec, which is not supposed to bottleneck the network (confirmed with scp).

**Comment by kaorahi** [comment]
Thx for nice suggestions!

I observed similar lags when I set `"analyze_interval_centisec": 1` in my `config.json`. So I fixed it by skipping too frequent renderings that will cause overflow of drawing capacity. Would you try 3c0eef37?

**Comment by isty2e** [comment]
Thanks! I'll try later. By the way, it seems like KataGo supports maxmoves as an agrument in lz-analyze and kata-analyze, as shown in [here](https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md). Probably no need for manual filtering?

**Comment by kaorahi** [comment]
You can toggle "Debug log" in [Debug] menu if you run LizGoban with the command `npm start` on a console. Have you checked it?

And/Or, you can modify src/engine.js from

~~~
`${analyzer} interval ${arg.analyze_interval_centisec} minmoves ${arg.minimum_suggested_moves}` :
~~~

to

~~~
`${analyzer} interval ${arg.analyze_interval_centisec} maxmoves 3` :
~~~

for testing whether long outputs are really harmful.

(BTW, edits of old comments are not noticed by email and I may miss them for a while.)

**Comment by isty2e** [comment]
I already have made a maxmoves tweak to my local copy of LizGoban by myself. However, it does not solve the problem at high visit counts, whose origin is still unclear for me.

For the debug log, the time intervals between `info move` lines is apparently increasing as visit count increases:

[debug_log.txt](https://github.com/kaorahi/lizgoban/files/4301575/debug_log.txt)

The time interval reduces to its normal value when a move is played and it has relatively small number of nodes, or the analysis is reset by changing komi or resetting the engine, etc.

**Comment by kaorahi** [comment]
I added more debug logs into debug_issue45 branch. Would you try dd6c9b50?

**Comment by isty2e** [comment]
[debug_log.txt](https://github.com/kaorahi/lizgoban/files/4301605/debug_log.txt)

Here it is. I didn't change any config from default, nor maxmoves option is applied here. Apparently the interval between processing and receiving the `kata-analyze` result is increasing, and the length of string is increasing as well.

**Comment by isty2e** [comment]
A similar phenomenon occurs for the local installation of KataGo as well - the time interval between `info move` constantly increases as more visits accumulate. Maybe the bottleneck is not network but stdout?

**Comment by kaorahi** [comment]
It seems that lizgoban processes each "info..." line within 0.2 sec. or so...

To check katago's behavior without lizgoban, would you try `node debug_issue45.js` in c7eac957? It is a minimal script that only shows the results of kata-analyze. Please edit its header as you like.

**Comment by isty2e** [comment]
[debug_log.txt](https://github.com/kaorahi/lizgoban/files/4301676/debug_log.txt)

Here it is.

**Comment by kaorahi** [comment]
thx. I added an idle loop into debug_issue45.js to emulate overheads of lizgoban (6d3e3470). Can you reproduce lags at high visit counts with it?

If "no", I am not sure what is the critical difference between debug_issue45.js and lizgoban.

**Comment by isty2e** [comment]
[debug_log.txt](https://github.com/kaorahi/lizgoban/files/4301762/debug_log.txt)

Apparently the answer is "yes" - exactly the same symptom.

**Comment by kaorahi** [comment]
Then what about `use_each_line = false` and/or `overhead_centisec = 10`? I would like to know the minimum condition for the symptom.

**Comment by isty2e** [comment]
They don't seem like affecting it, as well as the combination of both.

**Comment by isty2e** [comment]
[processed.txt](https://github.com/kaorahi/lizgoban/files/4301804/processed.txt)

A bit of profiling info, though I'm not sure if it will help...

**Comment by kaorahi** [comment]
(1)
I added setTimeout trick to the line parser of lizgoban as a trial. Does it work?

(2)
Sorry. `idle_loop` was called twice or more for a single "info..." line if `use_each_line = false`. I updated `debug_issue45.js`.

To clarify the condition, would you confirm a rough limit value of `overhead_centisec` that causes lags in the new `debug_issue45.js`? For example, is `overhead_centisec = 15` safe?

I am confused by the fact that you got lags even when lizgoban finished its processing within the analysis interval in https://github.com/kaorahi/lizgoban/issues/45#issuecomment-596065921

**Comment by isty2e** [comment]
(1)
Unfortunately it does not help.

(2)
The lagging seems having nothing to do with `overhead_centisec`: I tested in [1, 100] range, but it lags anyways.

**Comment by kaorahi** [comment]
Confused further... What about `overhead_centisec = 0`?

At present:
* lag: minimal javascript with overhead_centisec >= 1 https://github.com/kaorahi/lizgoban/issues/45#issuecomment-596093830
* no lag: SSH console without GUI https://github.com/kaorahi/lizgoban/issues/45#issuecomment-595746084

(Which was https://github.com/kaorahi/lizgoban/issues/45#issuecomment-596070869 ?)

So node.js may be the bottleneck??

**Comment by isty2e** [comment]
`overhead_centisec = 0` also leads to lagging.

I think it's more like this:

* No lag: Without `idle_loop` (terminal, the debug script before adding `idle_loop`)
* Lag: With `idle_loop` (regardless of `overhead_centisec` or `use_each_line`)

**Comment by isty2e** [comment]
Okay, after some further testing, it had nothing to do with `idle_loop`. The critical difference between two versions of scripts was `gtp_commands`: The older version was `lz-analyze interval 20\n` and a newer one was `kata-analyze interval 20 ownership true\n`. Especially, when `ownership true` was removed, the lag is almost gone. I still have no clue why it causes lagging for higher visits, hm.

**Comment by isty2e** [comment]
Some further investigation: `kata-analyze` itself is lagging when the number of visits are increased and `ownership true` option is applied. I think it is more like a problem of KataGo then.

**Comment by isty2e** [comment]
Sorry for inconvenience. It could be a temporary network lag for LZ then, presumably.

**Comment by kaorahi** [comment]
Thanks to this issue, a long-standing bug was fixed in 3c0eef37 and left/right keys seem to work smoother now. :-)
